services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      URL: photos.martinreinok.com
      VALIDATION: http
    ports:
      - 443:443
      - 80:80
    volumes:
      - ~/home-services/NGINX/swag-conf:/config
    restart: on-failure
    network_mode: host
